import './globals.css'
import 'swiper/css';
import 'swiper/css/pagination';
import type { Metadata } from 'next'
import Head from 'next/head';
import { Inter } from 'next/font/google'
import Header from "./layouts/Header"
import Footer from "./layouts/Footer"
import whatsappButton from "../../public/svg/whatsappButton.svg"
import Image from 'next/image'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: "Alejando Bacic,Ovalle,Odontologo,Implantología dental Ovalle, Implantes dentales en Ovalle,Odontólogo Ovalle, Clínica dental Ovalle, Servicios odontológicos en Ovalle, Odontología general Ovalle, Odontología estética Ovalle, Ortodoncia Ovalle, Implantes dentales Ovalle, Endodoncia Ovalle, Blanqueamiento dental Ovalle, Odontopediatría Ovalle, Odontólogo de confianza Ovalle, Cuidado dental Ovalle, Experiencia dental Ovalle, Tratamiento dental integral Ovalle, Salud bucal Ovalle"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">

      <body className={inter.className}>
        <Link target='__blank' href={"https://wa.me/935886949?text=Hola,%20Estoy%20Interesado%20en%20tus%20servicios%20odontologicos%20"} className='w-16 fixed bottom-4 rounded-full right-4 z-50 cursor-pointer animation-pulse hover:opacity-80'><Image src={whatsappButton} alt="btn_whatsapp" className=' rounded-full '></Image></Link>
        <Header />
        {children}
        <Footer />
      </body>

    </html>
  )
}
